"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-10-02 13:29:04.764421

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "facts_build",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source", sa.String(length=8), nullable=False),
        sa.Column("matches", sa.Integer(), nullable=False),
        sa.Column("built_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_facts_build")),
    )
    op.create_table(
        "game_map",
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("minimap_url", sa.String(length=255), nullable=False),
        sa.Column("x_multiplier", sa.Float(), nullable=False),
        sa.Column("y_multiplier", sa.Float(), nullable=False),
        sa.Column("x_scalar_to_add", sa.Float(), nullable=False),
        sa.Column("y_scalar_to_add", sa.Float(), nullable=False),
        sa.Column("callouts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("name", name=op.f("pk_game_map")),
    )
    op.create_table(
        "leaderboard_snapshot",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("region", sa.String(length=8), nullable=False),
        sa.Column("taken_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_leaderboard_snapshot")),
    )
    op.create_table(
        "match",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("source", sa.String(length=8), nullable=False),
        sa.Column("region", sa.String(length=8), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("map_name", sa.String(length=32), nullable=False),
        sa.Column("patch", sa.String(length=16), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("imported_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_match")),
    )
    op.create_index(op.f("ix_match_source"), "match", ["source"], unique=False)
    op.create_index(op.f("ix_match_started_at"), "match", ["started_at"], unique=False)
    op.create_table(
        "squad_player",
        sa.Column("puuid", sa.String(length=78), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("puuid", name=op.f("pk_squad_player")),
    )
    op.create_table(
        "win_probability",
        sa.Column("source", sa.String(length=8), nullable=False),
        sa.Column("own_alive", sa.Integer(), nullable=False),
        sa.Column("opp_alive", sa.Integer(), nullable=False),
        sa.Column("side", sa.String(length=4), nullable=False),
        sa.Column("planted", sa.Boolean(), nullable=False),
        sa.Column("wins", sa.Integer(), nullable=False),
        sa.Column("total", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("source", "own_alive", "opp_alive", "side", "planted", name=op.f("pk_win_probability")),
    )
    op.create_table(
        "death_fact",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("match_id", sa.String(length=36), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("patch", sa.String(length=16), nullable=False),
        sa.Column("map_name", sa.String(length=32), nullable=False),
        sa.Column("round_index", sa.Integer(), nullable=False),
        sa.Column("cohort", sa.String(length=8), nullable=False),
        sa.Column("team_id", sa.String(length=8), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("side", sa.String(length=4), nullable=False),
        sa.Column("ms", sa.Integer(), nullable=False),
        sa.Column("opening", sa.Boolean(), nullable=False),
        sa.Column("traded", sa.Boolean(), nullable=False),
        sa.Column("avenger", sa.String(length=64), nullable=True),
        sa.Column("callout", sa.String(length=64), nullable=False),
        sa.Column("damage", sa.Integer(), nullable=False),
        sa.Column("post_plant", sa.Boolean(), nullable=False),
        sa.Column("killer", sa.String(length=64), nullable=False),
        sa.Column("killer_cohort", sa.String(length=8), nullable=False),
        sa.Column("teamkill", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["match_id"], ["match.id"], name=op.f("fk_death_fact_match_id_match"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_death_fact")),
    )
    op.create_index(op.f("ix_death_fact_cohort"), "death_fact", ["cohort"], unique=False)
    op.create_index(op.f("ix_death_fact_match_id"), "death_fact", ["match_id"], unique=False)
    op.create_table(
        "player_match_fact",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("match_id", sa.String(length=36), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("patch", sa.String(length=16), nullable=False),
        sa.Column("map_name", sa.String(length=32), nullable=False),
        sa.Column("cohort", sa.String(length=8), nullable=False),
        sa.Column("team_id", sa.String(length=8), nullable=False),
        sa.Column("puuid", sa.String(length=78), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("agent", sa.String(length=32), nullable=False),
        sa.Column("rounds", sa.Integer(), nullable=False),
        sa.Column("won", sa.Boolean(), nullable=False),
        sa.Column("grenade_casts", sa.Integer(), nullable=False),
        sa.Column("ability1_casts", sa.Integer(), nullable=False),
        sa.Column("ability2_casts", sa.Integer(), nullable=False),
        sa.Column("ultimate_casts", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["match_id"], ["match.id"], name=op.f("fk_player_match_fact_match_id_match"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_player_match_fact")),
    )
    op.create_index(op.f("ix_player_match_fact_cohort"), "player_match_fact", ["cohort"], unique=False)
    op.create_index(op.f("ix_player_match_fact_match_id"), "player_match_fact", ["match_id"], unique=False)
    op.create_index(op.f("ix_player_match_fact_puuid"), "player_match_fact", ["puuid"], unique=False)
    op.create_table(
        "player_round_fact",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("match_id", sa.String(length=36), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("patch", sa.String(length=16), nullable=False),
        sa.Column("map_name", sa.String(length=32), nullable=False),
        sa.Column("round_index", sa.Integer(), nullable=False),
        sa.Column("cohort", sa.String(length=8), nullable=False),
        sa.Column("side", sa.String(length=4), nullable=False),
        sa.Column("puuid", sa.String(length=78), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("agent", sa.String(length=32), nullable=False),
        sa.Column("won", sa.Boolean(), nullable=False),
        sa.Column("match_won", sa.Boolean(), nullable=False),
        sa.Column("kills", sa.Integer(), nullable=False),
        sa.Column("deaths", sa.Integer(), nullable=False),
        sa.Column("assists", sa.Integer(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("damage", sa.Integer(), nullable=False),
        sa.Column("headshots", sa.Integer(), nullable=False),
        sa.Column("bodyshots", sa.Integer(), nullable=False),
        sa.Column("legshots", sa.Integer(), nullable=False),
        sa.Column("survived", sa.Boolean(), nullable=False),
        sa.Column("traded", sa.Boolean(), nullable=False),
        sa.Column("kast", sa.Boolean(), nullable=False),
        sa.Column("revenge_given", sa.Integer(), nullable=False),
        sa.Column("first_blood", sa.Boolean(), nullable=False),
        sa.Column("first_death", sa.Boolean(), nullable=False),
        sa.Column("first_blood_x", sa.Float(), nullable=True),
        sa.Column("first_blood_y", sa.Float(), nullable=True),
        sa.Column("first_death_x", sa.Float(), nullable=True),
        sa.Column("first_death_y", sa.Float(), nullable=True),
        sa.Column("clutch_versus", sa.Integer(), nullable=False),
        sa.Column("clutch_won", sa.Boolean(), nullable=False),
        sa.Column("win_probability_added", sa.Float(), nullable=False),
        sa.Column("death_ms", sa.Integer(), nullable=True),
        sa.Column("zero_damage_death", sa.Boolean(), nullable=False),
        sa.Column("weapon", sa.String(length=32), nullable=True),
        sa.Column("death_callout", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(["match_id"], ["match.id"], name=op.f("fk_player_round_fact_match_id_match"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_player_round_fact")),
    )
    op.create_index(op.f("ix_player_round_fact_cohort"), "player_round_fact", ["cohort"], unique=False)
    op.create_index(op.f("ix_player_round_fact_match_id"), "player_round_fact", ["match_id"], unique=False)
    op.create_index(op.f("ix_player_round_fact_puuid"), "player_round_fact", ["puuid"], unique=False)
    op.create_table(
        "round_fact",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("match_id", sa.String(length=36), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("patch", sa.String(length=16), nullable=False),
        sa.Column("map_name", sa.String(length=32), nullable=False),
        sa.Column("round_index", sa.Integer(), nullable=False),
        sa.Column("cohort", sa.String(length=8), nullable=False),
        sa.Column("team_id", sa.String(length=8), nullable=False),
        sa.Column("side", sa.String(length=4), nullable=False),
        sa.Column("won", sa.Boolean(), nullable=False),
        sa.Column("first_kill", sa.Boolean(), nullable=True),
        sa.Column("buy", sa.String(length=8), nullable=False),
        sa.Column("opp_buy", sa.String(length=8), nullable=False),
        sa.Column("max_advantage", sa.Integer(), nullable=False),
        sa.Column("min_advantage", sa.Integer(), nullable=False),
        sa.Column("planted", sa.Boolean(), nullable=False),
        sa.Column("plant_site", sa.String(length=4), nullable=True),
        sa.Column("advantage_at_plant", sa.Integer(), nullable=True),
        sa.Column("states", sa.ARRAY(sa.String(length=4)), nullable=False),
        sa.Column("result", sa.String(length=32), nullable=False),
        sa.Column("first_kill_ms", sa.Integer(), nullable=True),
        sa.Column("plant_ms", sa.Integer(), nullable=True),
        sa.Column("loadout", sa.Float(), nullable=False),
        sa.Column("opp_loadout", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["match_id"], ["match.id"], name=op.f("fk_round_fact_match_id_match"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_round_fact")),
    )
    op.create_index(op.f("ix_round_fact_cohort"), "round_fact", ["cohort"], unique=False)
    op.create_index(op.f("ix_round_fact_match_id"), "round_fact", ["match_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_round_fact_match_id"), table_name="round_fact")
    op.drop_index(op.f("ix_round_fact_cohort"), table_name="round_fact")
    op.drop_table("round_fact")
    op.drop_index(op.f("ix_player_round_fact_puuid"), table_name="player_round_fact")
    op.drop_index(op.f("ix_player_round_fact_match_id"), table_name="player_round_fact")
    op.drop_index(op.f("ix_player_round_fact_cohort"), table_name="player_round_fact")
    op.drop_table("player_round_fact")
    op.drop_index(op.f("ix_player_match_fact_puuid"), table_name="player_match_fact")
    op.drop_index(op.f("ix_player_match_fact_match_id"), table_name="player_match_fact")
    op.drop_index(op.f("ix_player_match_fact_cohort"), table_name="player_match_fact")
    op.drop_table("player_match_fact")
    op.drop_index(op.f("ix_death_fact_match_id"), table_name="death_fact")
    op.drop_index(op.f("ix_death_fact_cohort"), table_name="death_fact")
    op.drop_table("death_fact")
    op.drop_table("win_probability")
    op.drop_table("squad_player")
    op.drop_index(op.f("ix_match_started_at"), table_name="match")
    op.drop_index(op.f("ix_match_source"), table_name="match")
    op.drop_table("match")
    op.drop_table("leaderboard_snapshot")
    op.drop_table("game_map")
    op.drop_table("facts_build")
    # ### end Alembic commands ###
