"""report facts: kill and match facts, richer round and player facts

Facts are derived data: this migration clears them, run `uv run valostats rebuild-facts` afterwards.

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-03 10:48:19.079505

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# Derived tables emptied before their columns change; a rebuild fills them again.
FACT_TABLES = ("round_fact", "player_round_fact", "player_match_fact", "win_probability", "facts_build")

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | Sequence[str] | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _clear_facts() -> None:
    for table in FACT_TABLES:
        op.execute(sa.text(f"DELETE FROM {table}"))


def upgrade() -> None:
    """Upgrade schema."""
    _clear_facts()
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "kill_fact",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("match_id", sa.String(length=36), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("patch", sa.String(length=16), nullable=False),
        sa.Column("map_name", sa.String(length=32), nullable=False),
        sa.Column("round_index", sa.Integer(), nullable=False),
        sa.Column("ms", sa.Integer(), nullable=False),
        sa.Column("killer", sa.String(length=64), nullable=False),
        sa.Column("killer_puuid", sa.String(length=78), nullable=False),
        sa.Column("killer_team", sa.String(length=16), nullable=False),
        sa.Column("killer_cohort", sa.String(length=8), nullable=False),
        sa.Column("victim", sa.String(length=64), nullable=False),
        sa.Column("victim_puuid", sa.String(length=78), nullable=False),
        sa.Column("victim_team", sa.String(length=16), nullable=False),
        sa.Column("cohort", sa.String(length=8), nullable=False),
        sa.Column("victim_side", sa.String(length=4), nullable=False),
        sa.Column("weapon", sa.String(length=32), nullable=True),
        sa.Column("means", sa.String(length=8), nullable=False),
        sa.Column("secondary_fire", sa.Boolean(), nullable=False),
        sa.Column("assistants", sa.ARRAY(sa.String(length=64)), nullable=False),
        sa.Column("victim_x", sa.Float(), nullable=False),
        sa.Column("victim_y", sa.Float(), nullable=False),
        sa.Column("killer_x", sa.Float(), nullable=True),
        sa.Column("killer_y", sa.Float(), nullable=True),
        sa.Column("victim_zone", sa.String(length=64), nullable=False),
        sa.Column("killer_zone", sa.String(length=64), nullable=True),
        sa.Column("distance", sa.Float(), nullable=True),
        sa.Column("nearest_teammate", sa.Float(), nullable=True),
        sa.Column("team_spread", sa.Float(), nullable=True),
        sa.Column("opening", sa.Boolean(), nullable=False),
        sa.Column("avenged", sa.Boolean(), nullable=False),
        sa.Column("avenger", sa.String(length=64), nullable=True),
        sa.Column("avenge_ms", sa.Integer(), nullable=True),
        sa.Column("victim_team_alive", sa.Integer(), nullable=False),
        sa.Column("killer_team_alive", sa.Integer(), nullable=False),
        sa.Column("post_plant", sa.Boolean(), nullable=False),
        sa.Column("victim_damage", sa.Integer(), nullable=False),
        sa.Column("teamkill", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["match_id"], ["match.id"], name=op.f("fk_kill_fact_match_id_match"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_kill_fact")),
    )
    op.create_index(op.f("ix_kill_fact_cohort"), "kill_fact", ["cohort"], unique=False)
    op.create_index(op.f("ix_kill_fact_killer_cohort"), "kill_fact", ["killer_cohort"], unique=False)
    op.create_index(op.f("ix_kill_fact_match_id"), "kill_fact", ["match_id"], unique=False)
    op.create_table(
        "match_fact",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("match_id", sa.String(length=36), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("patch", sa.String(length=16), nullable=False),
        sa.Column("map_name", sa.String(length=32), nullable=False),
        sa.Column("cohort", sa.String(length=8), nullable=False),
        sa.Column("team_id", sa.String(length=8), nullable=False),
        sa.Column("won", sa.Boolean(), nullable=False),
        sa.Column("rounds_won", sa.Integer(), nullable=False),
        sa.Column("rounds_lost", sa.Integer(), nullable=False),
        sa.Column("start_side", sa.String(length=4), nullable=False),
        sa.Column("lineup", sa.ARRAY(sa.String(length=64)), nullable=False),
        sa.Column("agents", sa.ARRAY(sa.String(length=32)), nullable=False),
        sa.Column("opp_agents", sa.ARRAY(sa.String(length=32)), nullable=False),
        sa.Column("tier", sa.Float(), nullable=True),
        sa.Column("opp_tier", sa.Float(), nullable=True),
        sa.Column("length_ms", sa.Integer(), nullable=True),
        sa.Column("cluster", sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(["match_id"], ["match.id"], name=op.f("fk_match_fact_match_id_match"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_match_fact")),
    )
    op.create_index(op.f("ix_match_fact_cohort"), "match_fact", ["cohort"], unique=False)
    op.create_index(op.f("ix_match_fact_match_id"), "match_fact", ["match_id"], unique=False)
    op.drop_index(op.f("ix_death_fact_cohort"), table_name="death_fact")
    op.drop_index(op.f("ix_death_fact_match_id"), table_name="death_fact")
    op.drop_table("death_fact")
    op.add_column("player_match_fact", sa.Column("score", sa.Integer(), nullable=False))
    op.add_column("player_match_fact", sa.Column("tier_id", sa.Integer(), nullable=True))
    op.add_column("player_match_fact", sa.Column("tier_name", sa.String(length=32), nullable=True))
    op.add_column("player_round_fact", sa.Column("damage_received", sa.Integer(), nullable=False))
    op.add_column("player_round_fact", sa.Column("headshots_received", sa.Integer(), nullable=False))
    op.add_column("player_round_fact", sa.Column("bodyshots_received", sa.Integer(), nullable=False))
    op.add_column("player_round_fact", sa.Column("legshots_received", sa.Integer(), nullable=False))
    op.add_column("player_round_fact", sa.Column("kills_outnumbered", sa.Integer(), nullable=False))
    op.add_column("player_round_fact", sa.Column("multikill_span_ms", sa.Integer(), nullable=True))
    op.add_column("player_round_fact", sa.Column("armor", sa.String(length=32), nullable=True))
    op.add_column("player_round_fact", sa.Column("loadout", sa.Integer(), nullable=False))
    op.add_column("player_round_fact", sa.Column("remaining", sa.Integer(), nullable=False))
    op.add_column("player_round_fact", sa.Column("afk", sa.Boolean(), nullable=False))
    op.add_column("player_round_fact", sa.Column("penalty", sa.Boolean(), nullable=False))
    op.add_column("round_fact", sa.Column("first_death_avenged", sa.Boolean(), nullable=True))
    op.add_column("round_fact", sa.Column("plant_x", sa.Float(), nullable=True))
    op.add_column("round_fact", sa.Column("plant_y", sa.Float(), nullable=True))
    op.add_column("round_fact", sa.Column("planter", sa.String(length=64), nullable=True))
    op.add_column("round_fact", sa.Column("defused", sa.Boolean(), nullable=False))
    op.add_column("round_fact", sa.Column("defuser", sa.String(length=64), nullable=True))
    op.add_column("round_fact", sa.Column("ceremony", sa.String(length=32), nullable=True))
    op.add_column("round_fact", sa.Column("timeout", sa.Boolean(), nullable=False))
    op.add_column("round_fact", sa.Column("last_event_ms", sa.Integer(), nullable=False))
    op.add_column("round_fact", sa.Column("alive_end", sa.Integer(), nullable=False))
    op.add_column("round_fact", sa.Column("opp_alive_end", sa.Integer(), nullable=False))
    op.add_column("round_fact", sa.Column("score_diff", sa.Integer(), nullable=False))
    op.add_column("round_fact", sa.Column("previous_won", sa.Boolean(), nullable=True))
    op.add_column("round_fact", sa.Column("previous_losses", sa.Integer(), nullable=False))
    op.add_column("round_fact", sa.Column("pistol_won", sa.Boolean(), nullable=True))
    op.add_column("round_fact", sa.Column("second_round_won", sa.Boolean(), nullable=True))
    op.add_column("round_fact", sa.Column("match_won", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    _clear_facts()
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("round_fact", "match_won")
    op.drop_column("round_fact", "second_round_won")
    op.drop_column("round_fact", "pistol_won")
    op.drop_column("round_fact", "previous_losses")
    op.drop_column("round_fact", "previous_won")
    op.drop_column("round_fact", "score_diff")
    op.drop_column("round_fact", "opp_alive_end")
    op.drop_column("round_fact", "alive_end")
    op.drop_column("round_fact", "last_event_ms")
    op.drop_column("round_fact", "timeout")
    op.drop_column("round_fact", "ceremony")
    op.drop_column("round_fact", "defuser")
    op.drop_column("round_fact", "defused")
    op.drop_column("round_fact", "planter")
    op.drop_column("round_fact", "plant_y")
    op.drop_column("round_fact", "plant_x")
    op.drop_column("round_fact", "first_death_avenged")
    op.drop_column("player_round_fact", "penalty")
    op.drop_column("player_round_fact", "afk")
    op.drop_column("player_round_fact", "remaining")
    op.drop_column("player_round_fact", "loadout")
    op.drop_column("player_round_fact", "armor")
    op.drop_column("player_round_fact", "multikill_span_ms")
    op.drop_column("player_round_fact", "kills_outnumbered")
    op.drop_column("player_round_fact", "legshots_received")
    op.drop_column("player_round_fact", "bodyshots_received")
    op.drop_column("player_round_fact", "headshots_received")
    op.drop_column("player_round_fact", "damage_received")
    op.drop_column("player_match_fact", "tier_name")
    op.drop_column("player_match_fact", "tier_id")
    op.drop_column("player_match_fact", "score")
    op.create_table(
        "death_fact",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("match_id", sa.VARCHAR(length=36), autoincrement=False, nullable=False),
        sa.Column("started_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
        sa.Column("patch", sa.VARCHAR(length=16), autoincrement=False, nullable=False),
        sa.Column("map_name", sa.VARCHAR(length=32), autoincrement=False, nullable=False),
        sa.Column("round_index", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("cohort", sa.VARCHAR(length=8), autoincrement=False, nullable=False),
        sa.Column("team_id", sa.VARCHAR(length=8), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("side", sa.VARCHAR(length=4), autoincrement=False, nullable=False),
        sa.Column("ms", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("opening", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("traded", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("avenger", sa.VARCHAR(length=64), autoincrement=False, nullable=True),
        sa.Column("callout", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("damage", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("post_plant", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("killer", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("killer_cohort", sa.VARCHAR(length=8), autoincrement=False, nullable=False),
        sa.Column("teamkill", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(["match_id"], ["match.id"], name=op.f("fk_death_fact_match_id_match"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_death_fact")),
    )
    op.create_index(op.f("ix_death_fact_match_id"), "death_fact", ["match_id"], unique=False)
    op.create_index(op.f("ix_death_fact_cohort"), "death_fact", ["cohort"], unique=False)
    op.drop_index(op.f("ix_match_fact_match_id"), table_name="match_fact")
    op.drop_index(op.f("ix_match_fact_cohort"), table_name="match_fact")
    op.drop_table("match_fact")
    op.drop_index(op.f("ix_kill_fact_match_id"), table_name="kill_fact")
    op.drop_index(op.f("ix_kill_fact_killer_cohort"), table_name="kill_fact")
    op.drop_index(op.f("ix_kill_fact_cohort"), table_name="kill_fact")
    op.drop_table("kill_fact")
    # ### end Alembic commands ###
